= domake(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: Docker Make Manual
:man source: domake 2

== NAME

domake - maintain program dependencies running commands in container

== SYNOPSIS

*domake* [OPTIONS] [TARGET...]

== DESCRIPTION

Runs on top of *make(1)* using *dosh(1)* as default _shell_.

For a more thorough description of *make(1)*, please refers to its manual.

== OPTIONS

**--dockerfile FILE**::
	Path to the Dockerfile to use.

**--platform TARGET**::
	Set target platform.

**-C or --directory DIR**::
	Change to directory before doing anything else.

**--shell SHELL**::
	Set shell interpretor.
	Equivalent to set DOSHELL=<SHELL>.

**--version**::
	Print version.

**--help**::
	Print usage.

== ENVIRONMENT VARIABLES

**DOSHELL**::
	The full pathname to the shell to run in docker image.
	Equivalent to --shell <SHELL>.

**DOSH_PLATFORM**::
	The target platform to use.
	Equivalent to --platform <TARGET>.

**DOSHELL_DOCKER**::
	The docker executable.

== EXAMPLES

Run every shell _command_ in container

	$ domake
	asciidoctor -b manpage -o domake.1 domake.1.adoc
	gzip -c domake.1 >domake.1.gz
	Ubuntu
	rm domake.1
	27ab66448896e60b0d68bb2b14b1771813b34f51ee77652594b4d119efcf0405

Specify the *Dockerfile(5)* to use

	$ domake --dockerfile Dockerfile.fedora
	asciidoctor -b manpage -o domake.1 domake.1.adoc
	gzip -c domake.1 >domake.1.gz
	Fedora
	rm domake.1
	27ab66448896e60b0d68bb2b14b1771813b34f51ee77652594b4d119efcf0405

Change to another _directory_ before doing anything else

	$ cd /tmp
	$ domake -C "$OLDPWD"
	make: Entering directory '/home/gportay/src/domake'
	Ubuntu
	make: Leaving directory '/home/gportay/src/domake'
	1395ea836747e96dae36208d74e5cb4e006395beb6bb777c403635bbb0577072
	$ cd -

== PATCHES

Submit patches at *https://github.com/gportay/domake/pulls*

== BUGS

Report bugs at *https://github.com/gportay/domake/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright 2017-2018,2020,2024-2025 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

make(1), dosh(1)
