= domake(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: Docker Make Manual
:man source: domake 1

== NAME

domake - maintain program dependencies running commands in container

== SYNOPSIS

*domake* [OPTIONS] [TARGET...]

== DESCRIPTION

Runs on top of *make(1)* using *dosh(1)* as default _shell_.

For a more thorough description of *make(1)*, please refers to its manual.

== OPTIONS

**--dockerfile FILE**
	Path to the Dockerfile to use.

**-C or --directory DIR**
	Change to directory before doing anything else.

**--shell SHELL**
	Set shell interpretor.
	Equivalent to set DOSHELL=<SHELL>.

**--version**
	Print version.

**--help**
	Print usage.

== ENVIRONMENT VARIABLES

**DOCKER**
	The docker executable.

**DOSHELL**
	The full pathname to the shell to run in docker image.
	Equivalent to --shell <SHELL>.

== EXAMPLES

Run every shell _command_ in container

	$ domake
	asciidoctor -b manpage -o domake.1 domake.1.adoc
	gzip -c domake.1 >domake.1.gz
	Ubuntu
	rm domake.1
	27ab66448896e60b0d68bb2b14b1771813b34f51ee77652594b4d119efcf0405

Specify the *Dockerfile(5)* to use

	$ domake --dockerfile Dockerfile.fedora
	asciidoctor -b manpage -o domake.1 domake.1.adoc
	gzip -c domake.1 >domake.1.gz
	Fedora
	rm domake.1
	27ab66448896e60b0d68bb2b14b1771813b34f51ee77652594b4d119efcf0405

Change to another _directory_ before doing anything else

	$ cd /tmp
	$ domake -C "$OLDPWD"
	make: Entering directory '/home/gportay/src/domake'
	Ubuntu
	make: Leaving directory '/home/gportay/src/domake'
	1395ea836747e96dae36208d74e5cb4e006395beb6bb777c403635bbb0577072
	$ cd -

== BUGS

Report bugs at *https://github.com/gportay/domake/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2017-2018,2020 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the MIT License.

== SEE ALSO

make(1), dosh(1)
